# Generated by Django 4.1.2 on 2022-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_descriprion_coursecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='facults',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='cousre_img',
            field=models.ImageField(blank=True, null=True, upload_to='course_imgs/'),
        ),
    ]
