# Generated by Django 4.1.2 on 2022-11-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_facults_alter_course_cousre_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='facults',
        ),
    ]
